version: "3.7"

networks:
  # frontend:
  #   driver: bridge
  #   external: true

  backend:
    driver: bridge

services:
  nginx:
    image: nginx:1.15.4
    ports:
      - "80:80"
    volumes:
      - "./src/:/var/www/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - backend
    depends_on:
      - fpm

  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /sbin/docker-entrypoint_dev.sh
    volumes:
      - ./src/:/var/www/app/
      - ./docker-entrypoint_dev.sh:/sbin/docker-entrypoint_dev.sh
    networks:
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - backend

  redis:
    image: redis:5.0.4
    volumes:
      - "./redis:/data"
    networks:
      - backend

volumes:
  db:

