version: "3.7"

networks:
  default:
    driver: bridge

services:
  nginx:
    image: nginx:1.15.4
    ports:
      - "80:80"
    volumes:
      - "./example-app/:/var/www/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example-app/:/var/www/app/
    networks:
      - default
